# Generated by Django 4.2.7 on 2023-11-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.ImageField(upload_to='menus'),
        ),
    ]
