# Generated by Django 4.2.7 on 2023-11-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(null=True, upload_to='food_item'),
        ),
    ]
