# Generated by Django 4.2.7 on 2023-11-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cooked', 'Cooked'), ('Delivered', 'Delivered'), ('Cancalled', 'Cancalled')], default='Pending', max_length=50),
        ),
    ]
